// Generated from @browser-ui/shaders. Do not edit this file directly.
import CoreGraphics

public enum BrowserOperatingShaderVariant: String, CaseIterable, Sendable {
    case subtle
    case prism
    case pulse
    case tide

    public var defaults: (direction: BrowserOperatingShaderDirection, speed: BrowserOperatingShaderSpeed) {
        switch self {
        case .subtle: (.leftToRight, .slow)
        case .prism: (.leftToRight, .slow)
        case .pulse: (.leftToRight, .fast)
        case .tide: (.topLeftToBottomRight, .fast)
        }
    }
}

public enum BrowserOperatingShaderDirection: String, CaseIterable, Sendable {
    case leftToRight = "left-to-right"
    case rightToLeft = "right-to-left"
    case topToBottom = "top-to-bottom"
    case bottomToTop = "bottom-to-top"
    case topLeftToBottomRight = "top-left-to-bottom-right"
    case topRightToBottomLeft = "top-right-to-bottom-left"
    case bottomLeftToTopRight = "bottom-left-to-top-right"
    case bottomRightToTopLeft = "bottom-right-to-top-left"

    public var vector: CGVector {
        switch self {
        case .leftToRight: CGVector(dx: 1, dy: 0)
        case .rightToLeft: CGVector(dx: -1, dy: 0)
        case .topToBottom: CGVector(dx: 0, dy: -1)
        case .bottomToTop: CGVector(dx: 0, dy: 1)
        case .topLeftToBottomRight: CGVector(dx: 1, dy: -1)
        case .topRightToBottomLeft: CGVector(dx: -1, dy: -1)
        case .bottomLeftToTopRight: CGVector(dx: 1, dy: 1)
        case .bottomRightToTopLeft: CGVector(dx: -1, dy: 1)
        }
    }
}

public enum BrowserOperatingShaderSpeed: String, CaseIterable, Sendable {
    case slow
    case fast

    public var durationSeconds: Float {
        switch self {
        case .slow: 15
        case .fast: 7
        }
    }
}
