// Generated from @browser-ui/shaders. Do not edit this file directly.
#include <metal_stdlib>
using namespace metal;

constant float browserSubtlePI = 3.14159265359;

float3 browserSubtlePalette(float t, float3 a, float3 b, float3 c, float3 d) {
  return a + b * cos(2.0 * browserSubtlePI * (c * t + d));
}

float3 browserSubtleLivingPalette(float t, float time) {
  float3 prism = browserSubtlePalette(t, float3(0.46, 0.88, 0.33), float3(0.60, 0.58, 0.74), float3(0.50), float3(0.54, 0.22, 0.84));
  float3 lagoon = browserSubtlePalette(t, float3(0.58, 0.64, 0.52), float3(0.64, 0.30, 0.50), float3(0.50), float3(0.37, 0.66, 0.89));
  float3 berry = browserSubtlePalette(t, float3(0.92, 0.36, 0.56), float3(0.10, 0.14, 0.37), float3(0.50), float3(0.84, 0.11, 0.50));
  float phase = fmod(time * 0.08, 3.0);
  if (phase < 1.0) return mix(prism, lagoon, smoothstep(0.0, 1.0, phase));
  if (phase < 2.0) return mix(lagoon, berry, smoothstep(1.0, 2.0, phase));
  return mix(berry, prism, smoothstep(2.0, 3.0, phase));
}

[[ stitchable ]] half4 browserOperatingShader(
    float2 fragmentPosition,
    half4 sourceColor,
    float2 resolution,
    float time
) {
  float2 uv = fragmentPosition / resolution;
  float aspect = resolution.x / max(resolution.y, 1.0);
  float sweep = -0.25 + 1.5 * fract(time * 0.055);
  float ripple = 0.026 * sin(uv.y * 8.0 + time * 0.72) + 0.012 * sin(uv.y * 19.0 - time * 0.38);
  float distanceToSweep = abs(uv.x - sweep - ripple);
  float core = exp(-distanceToSweep * distanceToSweep * 82.0);
  float bloom = exp(-distanceToSweep * distanceToSweep * 12.0);
  float texture = 0.72 + 0.28 * sin(uv.y * 16.0 + time * 0.84 + sin(uv.y * 5.0 - time * 0.3));
  float2 glowCenter = float2(0.5 + 0.3 * sin(time * 0.17), 0.52 + 0.24 * cos(time * 0.13));
  float2 glowDelta = (uv - glowCenter) * float2(aspect, 1.0);
  float ambientGlow = exp(-dot(glowDelta, glowDelta) * 3.8);
  float palettePosition = uv.x * 0.74 + uv.y * 0.2 + ripple * 1.8 + time * 0.035;
  float3 colour = browserSubtleLivingPalette(palettePosition, time) * 0.5 + browserSubtleLivingPalette(palettePosition - 0.16, time) * 0.25 + browserSubtleLivingPalette(palettePosition + 0.16, time) * 0.25;
  float3 ambientColour = browserSubtleLivingPalette(palettePosition + 0.38 + ambientGlow * 0.2, time);
  colour = mix(ambientColour, colour, 0.45 + bloom * 0.55);
  colour *= 0.86 + core * texture * 0.3;
  float alpha = 0.028 + ambientGlow * 0.055 + bloom * 0.1 + core * 0.16;
  return half4(half3(colour * alpha), half(alpha));
}

constant float browserPrismPI = 3.14159265359;

float3 browserPrismPalette(float t, float3 a, float3 b, float3 c, float3 d) {
  return a + b * cos(2.0 * browserPrismPI * (c * t + d));
}

[[ stitchable ]] half4 browserOperatingPrismShader(
    float2 fragmentPosition,
    half4 sourceColor,
    float2 resolution,
    float time,
    float2 directionInput,
    float speed
) {
  float2 uv = fragmentPosition / resolution;
  float2 direction = normalize(directionInput);
  float2 perpendicular = float2(-direction.y, direction.x);
  float directionExtent = abs(direction.x) + abs(direction.y);
  float perpendicularExtent = abs(perpendicular.x) + abs(perpendicular.y);
  float axis = dot(uv - 0.5, direction) / directionExtent + 0.5;
  float cross = dot(uv - 0.5, perpendicular) / perpendicularExtent + 0.5;
  float rawCycle = time * speed + 0.000;
  float cycle = fract(rawCycle);
  // Keep consecutive sweeps exactly one viewport apart so the outgoing and
  // incoming edges remain visible together at the loop boundary.
  const float loopSpan = 1.0;
  float position = cycle;
  float wave = (
      sin(cross * 6.0 + time * 0.46) * 0.022
    + sin(cross * 13.0 - time * 0.3 + 1.4) * 0.012
    + sin(cross * 21.0 + time * 0.2 + 2.6) * 0.005
  ) * 0.900;
  float primaryDistance = (axis - position) - wave;
  float3 distances = float3(primaryDistance, primaryDistance - loopSpan, primaryDistance + loopSpan);
  float3 bodyLayers = exp(-distances * distances * 14.0);
  float3 crestLayers = exp(-distances * distances * 96.0);
  float3 trailLayers = step(distances, float3(0.0)) * exp(distances * 6.4);
  float body = min(dot(bodyLayers, float3(1.0)), 1.0);
  float crest = min(dot(crestLayers, float3(1.0)), 1.0);
  float trail = min(dot(trailLayers, float3(1.0)), 1.0);
  float slope = dot(-2.0 * distances * 14.0 * bodyLayers, float3(1.0));
  float2 normalSlope = -direction * slope * 0.2;
  float3 normal = normalize(float3(normalSlope, 1.0));
  float3 halfVector = normalize(float3(0.32, 0.48, 1.8));
  float specular = pow(max(dot(normal, halfVector), 0.0), 68.0);
  float fresnel = pow(1.0 - max(normal.z, 0.0), 2.6);
  float phase = dot(normal.xy, float2(0.42, 0.34)) + axis * 1.22 + cross * 0.28 + time * 0.04;
  float3 colour = browserPrismPalette(
    phase,
    float3(0.520, 0.520, 0.520),
    float3(0.500, 0.500, 0.500),
    float3(1.000, 1.000, 1.000),
    float3(0.000, 0.330, 0.670)
  );
  colour = pow(max(colour, 0.0), float3(0.76)) * 1.200;
  float easedPulse = 0.86 - 0.14 * cos(2.0 * browserPrismPI * cycle);
  float temporalPulse = mix(1.0, easedPulse, 0.000);
  float alpha = (body * 0.29 + crest * 0.12 + trail * 0.045 + fresnel * body * 0.07) * temporalPulse;
  float3 highlight = float3(0.94, 0.98, 1.0) * specular * crest * 0.22 * temporalPulse;
  return half4(half3(colour * alpha + highlight), half(min(alpha + specular * crest * 0.1, 0.62)));
}

constant float browserPulsePI = 3.14159265359;

float3 browserPulsePalette(float t, float3 a, float3 b, float3 c, float3 d) {
  return a + b * cos(2.0 * browserPulsePI * (c * t + d));
}

[[ stitchable ]] half4 browserOperatingPulseShader(
    float2 fragmentPosition,
    half4 sourceColor,
    float2 resolution,
    float time,
    float2 directionInput,
    float speed
) {
  float2 uv = fragmentPosition / resolution;
  float2 direction = normalize(directionInput);
  float2 perpendicular = float2(-direction.y, direction.x);
  float directionExtent = abs(direction.x) + abs(direction.y);
  float perpendicularExtent = abs(perpendicular.x) + abs(perpendicular.y);
  float axis = dot(uv - 0.5, direction) / directionExtent + 0.5;
  float cross = dot(uv - 0.5, perpendicular) / perpendicularExtent + 0.5;
  float rawCycle = time * speed + 0.400;
  float cycle = fract(rawCycle);
  // Keep consecutive sweeps exactly one viewport apart so the outgoing and
  // incoming edges remain visible together at the loop boundary.
  const float loopSpan = 1.0;
  float position = cycle;
  float wave = (
      sin(cross * 6.0 + time * 0.46) * 0.022
    + sin(cross * 13.0 - time * 0.3 + 1.4) * 0.012
    + sin(cross * 21.0 + time * 0.2 + 2.6) * 0.005
  ) * 0.820;
  float primaryDistance = (axis - position) - wave;
  float3 distances = float3(primaryDistance, primaryDistance - loopSpan, primaryDistance + loopSpan);
  float3 bodyLayers = exp(-distances * distances * 14.5);
  float3 crestLayers = exp(-distances * distances * 92.0);
  float3 trailLayers = step(distances, float3(0.0)) * exp(distances * 6.4);
  float body = min(dot(bodyLayers, float3(1.0)), 1.0);
  float crest = min(dot(crestLayers, float3(1.0)), 1.0);
  float trail = min(dot(trailLayers, float3(1.0)), 1.0);
  float slope = dot(-2.0 * distances * 14.5 * bodyLayers, float3(1.0));
  float2 normalSlope = -direction * slope * 0.2;
  float3 normal = normalize(float3(normalSlope, 1.0));
  float3 halfVector = normalize(float3(0.32, 0.48, 1.8));
  float specular = pow(max(dot(normal, halfVector), 0.0), 68.0);
  float fresnel = pow(1.0 - max(normal.z, 0.0), 2.6);
  float phase = dot(normal.xy, float2(0.42, 0.34)) + axis * 1.22 + cross * 0.28 + time * 0.04;
  float3 colour = browserPulsePalette(
    phase,
    float3(0.680, 0.250, 0.460),
    float3(0.330, 0.240, 0.380),
    float3(1.000, 0.820, 0.940),
    float3(0.040, 0.350, 0.580)
  );
  colour = pow(max(colour, 0.0), float3(0.76)) * 1.160;
  float easedPulse = 0.86 - 0.14 * cos(2.0 * browserPulsePI * cycle);
  float temporalPulse = mix(1.0, easedPulse, 1.000);
  float alpha = (body * 0.29 + crest * 0.12 + trail * 0.045 + fresnel * body * 0.07) * temporalPulse;
  float3 highlight = float3(0.94, 0.98, 1.0) * specular * crest * 0.22 * temporalPulse;
  return half4(half3(colour * alpha + highlight), half(min(alpha + specular * crest * 0.1, 0.62)));
}

constant float browserTidePI = 3.14159265359;

float3 browserTidePalette(float t, float3 a, float3 b, float3 c, float3 d) {
  return a + b * cos(2.0 * browserTidePI * (c * t + d));
}

[[ stitchable ]] half4 browserOperatingTideShader(
    float2 fragmentPosition,
    half4 sourceColor,
    float2 resolution,
    float time,
    float2 directionInput,
    float speed
) {
  float2 uv = fragmentPosition / resolution;
  float2 direction = normalize(directionInput);
  float2 perpendicular = float2(-direction.y, direction.x);
  float directionExtent = abs(direction.x) + abs(direction.y);
  float perpendicularExtent = abs(perpendicular.x) + abs(perpendicular.y);
  float axis = dot(uv - 0.5, direction) / directionExtent + 0.5;
  float cross = dot(uv - 0.5, perpendicular) / perpendicularExtent + 0.5;
  float rawCycle = time * speed + 0.720;
  float cycle = fract(rawCycle);
  // Keep consecutive sweeps exactly one viewport apart so the outgoing and
  // incoming edges remain visible together at the loop boundary.
  const float loopSpan = 1.0;
  float position = cycle;
  float wave = (
      sin(cross * 6.0 + time * 0.46) * 0.022
    + sin(cross * 13.0 - time * 0.3 + 1.4) * 0.012
    + sin(cross * 21.0 + time * 0.2 + 2.6) * 0.005
  ) * 0.820;
  float primaryDistance = (axis - position) - wave;
  float3 distances = float3(primaryDistance, primaryDistance - loopSpan, primaryDistance + loopSpan);
  float3 bodyLayers = exp(-distances * distances * 14.5);
  float3 crestLayers = exp(-distances * distances * 92.0);
  float3 trailLayers = step(distances, float3(0.0)) * exp(distances * 6.4);
  float body = min(dot(bodyLayers, float3(1.0)), 1.0);
  float crest = min(dot(crestLayers, float3(1.0)), 1.0);
  float trail = min(dot(trailLayers, float3(1.0)), 1.0);
  float slope = dot(-2.0 * distances * 14.5 * bodyLayers, float3(1.0));
  float2 normalSlope = -direction * slope * 0.2;
  float3 normal = normalize(float3(normalSlope, 1.0));
  float3 halfVector = normalize(float3(0.32, 0.48, 1.8));
  float specular = pow(max(dot(normal, halfVector), 0.0), 68.0);
  float fresnel = pow(1.0 - max(normal.z, 0.0), 2.6);
  float phase = dot(normal.xy, float2(0.42, 0.34)) + axis * 1.22 + cross * 0.28 + time * 0.04;
  float3 colour = browserTidePalette(
    phase,
    float3(0.220, 0.540, 0.550),
    float3(0.220, 0.420, 0.390),
    float3(0.860, 1.020, 0.820),
    float3(0.480, 0.200, 0.050)
  );
  colour = pow(max(colour, 0.0), float3(0.76)) * 1.220;
  float easedPulse = 0.86 - 0.14 * cos(2.0 * browserTidePI * cycle);
  float temporalPulse = mix(1.0, easedPulse, 1.000);
  float alpha = (body * 0.29 + crest * 0.12 + trail * 0.045 + fresnel * body * 0.07) * temporalPulse;
  float3 highlight = float3(0.94, 0.98, 1.0) * specular * crest * 0.22 * temporalPulse;
  return half4(half3(colour * alpha + highlight), half(min(alpha + specular * crest * 0.1, 0.62)));
}
