// Generated from @browser-ui/shaders. Do not edit this file directly.
#version 320 es

precision highp float;

#include <flutter/runtime_effect.glsl>

out vec4 frag_color;
uniform vec2 u_resolution;
uniform float u_time;
uniform vec2 u_direction;
uniform float u_speed;
const float PI = 3.14159265359;

vec3 palette(float t, vec3 a, vec3 b, vec3 c, vec3 d) {
  return a + b * cos(2.0 * PI * (c * t + d));
}

void main() {
  vec2 uv = FlutterFragCoord().xy / u_resolution;
  vec2 direction = normalize(u_direction);
  vec2 perpendicular = vec2(-direction.y, direction.x);
  float directionExtent = abs(direction.x) + abs(direction.y);
  float perpendicularExtent = abs(perpendicular.x) + abs(perpendicular.y);
  float axis = dot(uv - 0.5, direction) / directionExtent + 0.5;
  float cross = dot(uv - 0.5, perpendicular) / perpendicularExtent + 0.5;
  float rawCycle = u_time * u_speed + 0.000;
  float cycle = fract(rawCycle);
  // Keep consecutive sweeps exactly one viewport apart so the outgoing and
  // incoming edges remain visible together at the loop boundary.
  const float loopSpan = 1.0;
  float position = cycle;
  float wave = (
      sin(cross * 6.0 + u_time * 0.46) * 0.022
    + sin(cross * 13.0 - u_time * 0.3 + 1.4) * 0.012
    + sin(cross * 21.0 + u_time * 0.2 + 2.6) * 0.005
  ) * 0.900;
  float primaryDistance = (axis - position) - wave;
  vec3 distances = vec3(primaryDistance, primaryDistance - loopSpan, primaryDistance + loopSpan);
  vec3 bodyLayers = exp(-distances * distances * 14.0);
  vec3 crestLayers = exp(-distances * distances * 96.0);
  vec3 trailLayers = step(distances, vec3(0.0)) * exp(distances * 6.4);
  float body = min(dot(bodyLayers, vec3(1.0)), 1.0);
  float crest = min(dot(crestLayers, vec3(1.0)), 1.0);
  float trail = min(dot(trailLayers, vec3(1.0)), 1.0);
  float slope = dot(-2.0 * distances * 14.0 * bodyLayers, vec3(1.0));
  vec2 normalSlope = -direction * slope * 0.2;
  vec3 normal = normalize(vec3(normalSlope, 1.0));
  vec3 halfVector = normalize(vec3(0.32, 0.48, 1.8));
  float specular = pow(max(dot(normal, halfVector), 0.0), 68.0);
  float fresnel = pow(1.0 - max(normal.z, 0.0), 2.6);
  float phase = dot(normal.xy, vec2(0.42, 0.34)) + axis * 1.22 + cross * 0.28 + u_time * 0.04;
  vec3 colour = palette(
    phase,
    vec3(0.520, 0.520, 0.520),
    vec3(0.500, 0.500, 0.500),
    vec3(1.000, 1.000, 1.000),
    vec3(0.000, 0.330, 0.670)
  );
  colour = pow(max(colour, 0.0), vec3(0.76)) * 1.200;
  float easedPulse = 0.86 - 0.14 * cos(2.0 * PI * cycle);
  float temporalPulse = mix(1.0, easedPulse, 0.000);
  float alpha = (body * 0.29 + crest * 0.12 + trail * 0.045 + fresnel * body * 0.07) * temporalPulse;
  vec3 highlight = vec3(0.94, 0.98, 1.0) * specular * crest * 0.22 * temporalPulse;
  frag_color = vec4(colour * alpha + highlight, min(alpha + specular * crest * 0.1, 0.62));
}
