// Generated from @browser-ui/shaders. Do not edit this file directly.
enum BrowserOperatingShaderVariant {
  subtle,
  prism,
  pulse,
  tide;

  const BrowserOperatingShaderVariant();

  String get assetName => 'operating_$name.frag';

  BrowserOperatingShaderConfiguration get defaults => switch (this) {
    BrowserOperatingShaderVariant.subtle =>
      const BrowserOperatingShaderConfiguration(
        variant: BrowserOperatingShaderVariant.subtle,
        direction: BrowserOperatingShaderDirection.leftToRight,
        speed: BrowserOperatingShaderSpeed.slow,
      ),
    BrowserOperatingShaderVariant.prism =>
      const BrowserOperatingShaderConfiguration(
        variant: BrowserOperatingShaderVariant.prism,
        direction: BrowserOperatingShaderDirection.leftToRight,
        speed: BrowserOperatingShaderSpeed.slow,
      ),
    BrowserOperatingShaderVariant.pulse =>
      const BrowserOperatingShaderConfiguration(
        variant: BrowserOperatingShaderVariant.pulse,
        direction: BrowserOperatingShaderDirection.leftToRight,
        speed: BrowserOperatingShaderSpeed.fast,
      ),
    BrowserOperatingShaderVariant.tide =>
      const BrowserOperatingShaderConfiguration(
        variant: BrowserOperatingShaderVariant.tide,
        direction: BrowserOperatingShaderDirection.topLeftToBottomRight,
        speed: BrowserOperatingShaderSpeed.fast,
      ),
  };
}

enum BrowserOperatingShaderDirection {
  leftToRight('left-to-right'),
  rightToLeft('right-to-left'),
  topToBottom('top-to-bottom'),
  bottomToTop('bottom-to-top'),
  topLeftToBottomRight('top-left-to-bottom-right'),
  topRightToBottomLeft('top-right-to-bottom-left'),
  bottomLeftToTopRight('bottom-left-to-top-right'),
  bottomRightToTopLeft('bottom-right-to-top-left');

  const BrowserOperatingShaderDirection(this.id);

  final String id;

  ({double x, double y}) get vector => switch (this) {
    BrowserOperatingShaderDirection.leftToRight => (x: 1.0, y: 0.0),
    BrowserOperatingShaderDirection.rightToLeft => (x: -1.0, y: 0.0),
    BrowserOperatingShaderDirection.topToBottom => (x: 0.0, y: -1.0),
    BrowserOperatingShaderDirection.bottomToTop => (x: 0.0, y: 1.0),
    BrowserOperatingShaderDirection.topLeftToBottomRight => (x: 1.0, y: -1.0),
    BrowserOperatingShaderDirection.topRightToBottomLeft => (x: -1.0, y: -1.0),
    BrowserOperatingShaderDirection.bottomLeftToTopRight => (x: 1.0, y: 1.0),
    BrowserOperatingShaderDirection.bottomRightToTopLeft => (x: -1.0, y: 1.0),
  };
}

enum BrowserOperatingShaderSpeed {
  slow(15),
  fast(7);

  const BrowserOperatingShaderSpeed(this.durationSeconds);

  final double durationSeconds;
}

final class BrowserOperatingShaderConfiguration {
  const BrowserOperatingShaderConfiguration({
    this.variant = BrowserOperatingShaderVariant.subtle,
    this.direction,
    this.speed,
  });

  final BrowserOperatingShaderVariant variant;
  final BrowserOperatingShaderDirection? direction;
  final BrowserOperatingShaderSpeed? speed;

  BrowserOperatingShaderDirection get resolvedDirection =>
      direction ?? variant.defaults.direction!;

  BrowserOperatingShaderSpeed get resolvedSpeed =>
      speed ?? variant.defaults.speed!;
}
