function dartCase(identifier) {
  return identifier.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

export function dartConfigurationSource({
  directions,
  meta,
  speeds,
  variants,
}) {
  const variantCases = variants
    .map(
      (variant, index) =>
        `  ${variant}${index === variants.length - 1 ? ";" : ","}`,
    )
    .join("\n");
  const directionIds = Object.keys(directions);
  const directionCases = directionIds
    .map(
      (direction, index) =>
        `  ${dartCase(direction)}('${direction}')${index === directionIds.length - 1 ? ";" : ","}`,
    )
    .join("\n");
  const speedEntries = Object.entries(speeds);
  const speedCases = speedEntries
    .map(
      ([speed, definition], index) =>
        `  ${speed}(${definition.durationSeconds})${index === speedEntries.length - 1 ? ";" : ","}`,
    )
    .join("\n");
  const directionVectors = Object.entries(directions)
    .map(
      ([direction, definition]) =>
        `      BrowserOperatingShaderDirection.${dartCase(direction)} => (x: ${definition.vector[0].toFixed(1)}, y: ${definition.vector[1].toFixed(1)}),`,
    )
    .join("\n");
  const defaults = variants
    .map(
      (variant) =>
        `      BrowserOperatingShaderVariant.${variant} => const BrowserOperatingShaderConfiguration(` +
        `variant: BrowserOperatingShaderVariant.${variant}, ` +
        `direction: BrowserOperatingShaderDirection.${dartCase(meta[variant].defaultDirection)}, ` +
        `speed: BrowserOperatingShaderSpeed.${meta[variant].defaultSpeed}),`,
    )
    .join("\n");

  return `// Generated from @browser-ui/shaders. Do not edit this file directly.
enum BrowserOperatingShaderVariant {
${variantCases}

  const BrowserOperatingShaderVariant();

  String get assetName => 'operating_\$name.frag';

  BrowserOperatingShaderConfiguration get defaults => switch (this) {
${defaults}
    };
}

enum BrowserOperatingShaderDirection {
${directionCases}

  const BrowserOperatingShaderDirection(this.id);

  final String id;

  ({double x, double y}) get vector => switch (this) {
${directionVectors}
    };
}

enum BrowserOperatingShaderSpeed {
${speedCases}

  const BrowserOperatingShaderSpeed(this.durationSeconds);

  final double durationSeconds;
}

final class BrowserOperatingShaderConfiguration {
  const BrowserOperatingShaderConfiguration({
    this.variant = BrowserOperatingShaderVariant.subtle,
    this.direction,
    this.speed,
  });

  final BrowserOperatingShaderVariant variant;
  final BrowserOperatingShaderDirection? direction;
  final BrowserOperatingShaderSpeed? speed;

  BrowserOperatingShaderDirection get resolvedDirection =>
      direction ?? variant.defaults.direction!;

  BrowserOperatingShaderSpeed get resolvedSpeed => speed ?? variant.defaults.speed!;
}
`;
}
