const generatedHeader =
  "// Generated from @browser-ui/shaders. Do not edit this file directly.\n";

export function flutterFragmentSource(webGLSource) {
  const body = webGLSource
    .replace(
      "precision highp float;",
      "precision highp float;\n\n#include <flutter/runtime_effect.glsl>\n\nout vec4 frag_color;",
    )
    .replaceAll("gl_FragCoord.xy", "FlutterFragCoord().xy")
    .replaceAll("gl_FragColor", "frag_color");
  return `${generatedHeader}#version 320 es\n\n${body.trim()}\n`;
}
