const metalFunctionNames = {
  subtle: "browserOperatingShader",
  prism: "browserOperatingPrismShader",
  pulse: "browserOperatingPulseShader",
  tide: "browserOperatingTideShader",
};

function replaceIdentifier(source, identifier, replacement) {
  return source.replace(new RegExp(`\\b${identifier}\\b`, "g"), replacement);
}

export function metalFragmentBody(webGLSource, variant) {
  const prefix = `browser${variant[0].toUpperCase()}${variant.slice(1)}`;
  const parameters = variant === "subtle"
    ? "float2 resolution,\n    float time"
    : "float2 resolution,\n    float time,\n    float2 directionInput,\n    float speed";
  let body = webGLSource
    .replace(/^precision highp float;\n/m, "")
    .replace(/^uniform .+;\n/gm, "")
    .replace("void main()", `[[ stitchable ]] half4 ${metalFunctionNames[variant]}(\n    float2 fragmentPosition,\n    half4 sourceColor,\n    ${parameters}\n)`)
    .replaceAll("gl_FragCoord.xy", "fragmentPosition")
    .replace(
      "gl_FragColor = vec4(colour * alpha, alpha);",
      "return half4(half3(colour * alpha), half(alpha));",
    )
    .replace(
      "gl_FragColor = vec4(colour * alpha + highlight, min(alpha + specular * crest * 0.1, 0.62));",
      "return half4(half3(colour * alpha + highlight), half(min(alpha + specular * crest * 0.1, 0.62)));",
    )
    .replaceAll("vec2", "float2")
    .replaceAll("vec3", "float3")
    .replaceAll("mod(", "fmod(");

  for (const [identifier, replacement] of [
    ["u_resolution", "resolution"],
    ["u_time", "time"],
    ["u_direction", "directionInput"],
    ["u_speed", "speed"],
    ["livingPalette", `${prefix}LivingPalette`],
    ["palette", `${prefix}Palette`],
    ["PI", `${prefix}PI`],
  ]) {
    body = replaceIdentifier(body, identifier, replacement);
  }

  body = body.replace(`const float ${prefix}PI`, `constant float ${prefix}PI`);

  return body.trim();
}

export function metalLibrarySource(fragmentSources, variants) {
  const bodies = variants.map((variant) => metalFragmentBody(
    fragmentSources[variant],
    variant,
  ));
  return `// Generated from @browser-ui/shaders. Do not edit this file directly.\n#include <metal_stdlib>\nusing namespace metal;\n\n${bodies.join("\n\n")}\n`;
}
