function swiftCase(identifier) {
  return identifier.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

export function swiftConfigurationSource({
  directions,
  meta,
  speeds,
  variants,
}) {
  const variantCases = variants
    .map((variant) => `    case ${variant}`)
    .join("\n");
  const directionCases = Object.keys(directions)
    .map((direction) => `    case ${swiftCase(direction)} = "${direction}"`)
    .join("\n");
  const speedCases = Object.keys(speeds)
    .map((speed) => `    case ${speed}`)
    .join("\n");
  const directionVectors = Object.entries(directions)
    .map(
      ([direction, definition]) =>
        `        case .${swiftCase(direction)}: CGVector(dx: ${definition.vector[0]}, dy: ${definition.vector[1]})`,
    )
    .join("\n");
  const durations = Object.entries(speeds)
    .map(
      ([speed, definition]) =>
        `        case .${speed}: ${definition.durationSeconds}`,
    )
    .join("\n");
  const defaults = variants
    .map(
      (variant) =>
        `        case .${variant}: (.${swiftCase(meta[variant].defaultDirection)}, .${meta[variant].defaultSpeed})`,
    )
    .join("\n");

  return `// Generated from @browser-ui/shaders. Do not edit this file directly.
import CoreGraphics

public enum BrowserOperatingShaderVariant: String, CaseIterable, Sendable {
${variantCases}

    public var defaults: (direction: BrowserOperatingShaderDirection, speed: BrowserOperatingShaderSpeed) {
        switch self {
${defaults}
        }
    }
}

public enum BrowserOperatingShaderDirection: String, CaseIterable, Sendable {
${directionCases}

    public var vector: CGVector {
        switch self {
${directionVectors}
        }
    }
}

public enum BrowserOperatingShaderSpeed: String, CaseIterable, Sendable {
${speedCases}

    public var durationSeconds: Float {
        switch self {
${durations}
        }
    }
}
`;
}
